regions: 
  - eu-west-2
account-blacklist: 
  - "000000000000"

resource-types:
  targets: 
    - S3Bucket 
    - S3Object 

accounts:
  "999999999999":
    filters: 
      ACMCertificate: []
      ACMPCACertificateAuthority: []
      ACMPCACertificateAuthorityState: []
      APIGatewayAPIKey: []
      APIGatewayClientCertificate: []
      APIGatewayDomainName: []
      APIGatewayRestAPI: []
      APIGatewayUsagePlan: []
      APIGatewayVpcLink: []
      AppStreamDirectoryConfig: []
      AppStreamFleet: []
      AppStreamFleetState: []
      AppStreamImage: []
      AppStreamImageBuilder: []
      AppStreamImageBuilderWaiter: []
      AppStreamStack: []
      AppStreamStackFleetAttachment: []
      AutoScalingGroup: []
      AutoScalingPlansScalingPlan: []
      BatchComputeEnvironment: []
      BatchComputeEnvironmentState: []
      BatchJobQueue: []
      BatchJobQueueState: []
      Cloud9Environment: []
      CloudDirectoryDirectory: []
      CloudDirectorySchema: []
      CloudFormationStack: []
      CloudFrontDistribution: []
      CloudFrontDistributionDeployment: []
      CloudHSMV2Cluster: []
      CloudHSMV2ClusterHSM: []
      CloudSearchDomain: []
      CloudTrailTrail: []
      CloudWatchAlarm: []
      CloudWatchDashboard: []
      CloudWatchEventsRule: []
      CloudWatchEventsTarget: []
      CloudWatchLogsDestination: []
      CloudWatchLogsLogGroup: []
      CodeBuildProject: []
      CodeCommitRepository: []
      CodeDeployApplication: []
      CodePipelinePipeline: []
      CodeStarProject: []
      ConfigServiceConfigRule: []
      ConfigServiceConfigurationRecorder: []
      ConfigServiceDeliveryChannel: []
      DAXCluster: []
      DAXParameterGroup: []
      DAXSubnetGroup: []
      DataPipelinePipeline: []
      DatabaseMigrationServiceCertificate: []
      DatabaseMigrationServiceEndpoint: []
      DatabaseMigrationServiceEventSubscription: []
      DatabaseMigrationServiceReplicationInstance: []
      DatabaseMigrationServiceReplicationTask: []
      DatabaseMigrationServiceSubnetGroup: []
      DeviceFarmProject: []
      DirectoryServiceDirectory: []
      DynamoDBTable: []
      DynamoDBTableItem: []
      EC2Address: []
      EC2CustomerGateway: []
      EC2DHCPOption: []
      EC2Image: []
      EC2Instance: []
      EC2InternetGateway: []
      EC2InternetGatewayAttachment: []
      EC2KeyPair: []
      EC2NATGateway: []
      EC2NetworkACL: []
      EC2NetworkInterface: []
      EC2PlacementGroup: []
      EC2RouteTable: []
      EC2SecurityGroup: []
      EC2Snapshot: []
      EC2SpotFleetRequest: []
      EC2Subnet: []
      EC2VPC: []
      EC2VPCEndpoint: []
      EC2VPNConnection: []
      EC2VPNGateway: []
      EC2VPNGatewayAttachment: []
      EC2Volume: []
      ECRRepository: []
      ECSCluster: []
      ECSClusterInstance: []
      ECSService: []
      ECSTaskDefinition: []
      EFSFileSystem: []
      EFSMountTarget: []
      EKSCluster: []
      ELB: []
      ELBv2: []
      ELBv2TargetGroup: []
      EMRCluster: []
      EMRSecurityConfiguration: []
      ESDomain: []
      ElasticBeanstalkApplication: []
      ElasticBeanstalkEnvironment: []
      ElasticTranscoderPipeline: []
      ElasticacheCacheCluster: []
      ElasticacheSubnetGroup: []
      FirehoseDeliveryStream: []
      GlueClassifier: []
      GlueConnection: []
      GlueCrawler: []
      GlueDatabase: []
      GlueDevEndpoint: []
      GlueJob: []
      GlueTrigger: []
      IAMGroup: []
      IAMGroupPolicyAttachment: []
      IAMInstanceProfile: []
      IAMInstanceProfileRole: []
      IAMLoginProfile: []
      IAMPolicy: []
      IAMRole: []
      IAMRolePolicy: []
      IAMRolePolicyAttachment: []
      IAMServerCertificate: []
      IAMUser: []
      IAMUserAccessKey: []
      IAMUserGroupAttachment: []
      IAMUserPolicy: []
      IAMUserPolicyAttachment: []
      IoTAuthorizer: []
      IoTCACertificate: []
      IoTCertificate: []
      IoTJob: []
      IoTOTAUpdate: []
      IoTPolicy: []
      IoTRoleAlias: []
      IoTStream: []
      IoTThing: []
      IoTThingGroup: []
      IoTThingType: []
      IoTThingTypeState: []
      IoTTopicRule: []
      KMSAlias: []
      KMSKey: []
      KinesisAnalyticsApplication: []
      KinesisStream: []
      KinesisVideoProject: []
      LambdaFunction: []
      LaunchConfiguration: []
      LightsailDisk: []
      LightsailDomain: []
      LightsailInstance: []
      LightsailKeyPair: []
      LightsailLoadBalancer: []
      LightsailStaticIP: []
      MQBroker: []
      MachineLearningBranchPrediction: []
      MachineLearningDataSource: []
      MachineLearningEvaluation: []
      MachineLearningMLModel: []
      MediaConvertJobTemplate: []
      MediaConvertPreset: []
      MediaConvertQueue: []
      MediaLiveChannel: []
      MediaLiveInput: []
      MediaLiveInputSecurityGroup: []
      MediaPackageChannel: []
      MediaPackageOriginEndpoint: []
      MediaStoreContainer: []
      MediaStoreDataItems: []
      MediaTailorConfiguration: []
      MobileProject: []
      NeptuneCluster: []
      NeptuneInstance: []
      NetpuneSnapshot: []
      OpsWorksApp: []
      OpsWorksCMBackup: []
      OpsWorksCMServer: []
      OpsWorksCMServerState: []
      OpsWorksInstance: []
      OpsWorksLayer: []
      OpsWorksUserProfile: []
      RDSDBCluster: []
      RDSDBClusterParameterGroup: []
      RDSDBParameterGroup: []
      RDSDBSubnetGroup: []
      RDSInstance: []
      RDSSnapshot: []
      RedshiftCluster: []
      RedshiftParameterGroup: []
      RedshiftSnapshot: []
      RedshiftSubnetGroup: []
      RekognitionCollection: []
      ResourceGroupGroup: []
      Route53HostedZone: []
      Route53ResourceRecordSet: []
      S3Bucket: []
      S3MultipartUpload: []
      S3Object: []
      SESConfigurationSet: []
      SESIdentity: []
      SESReceiptFilter: []
      SESReceiptRuleSet: []
      SESTemplate: []
      SFNStateMachine: []
      SNSEndpoint: []
      SNSPlatformApplication: []
      SNSSubscription: []
      SNSTopic: []
      SQSQueue: []
      SSMActivation: []
      SSMAssociation: []
      SSMDocument: []
      SSMMaintenanceWindow: []
      SSMParameter: []
      SSMPatchBaseline: []
      SSMResourceDataSync: []
      SageMakerEndpoint: []
      SageMakerEndpointConfig: []
      SageMakerModel: []
      SageMakerNotebookInstance: []
      SageMakerNotebookInstanceState: []
      SecretsManagerSecret: []
      ServiceCatalogConstraintPortfolioAttachment: []
      ServiceCatalogPortfolio: []
      ServiceCatalogPortfolioProductAttachment: []
      ServiceCatalogPortfolioShareAttachment: []
      ServiceCatalogPrincipalPortfolioAttachment: []
      ServiceCatalogProduct: []
      ServiceCatalogProvisionedProduct: []
      ServiceCatalogTagOption: []
      ServiceCatalogTagOptionPortfolioAttachment: []
      ServiceDiscoveryInstance: []
      ServiceDiscoveryNamespace: []
      ServiceDiscoveryService: []
      SimpleDBDomain: []
      StorageGatewayFileShare: []
      StorageGatewayGateway: []
      StorageGatewayTape: []
      StorageGatewayVolume: []
      WAFRegionalByteMatchSet: []
      WAFRegionalByteMatchSetIP: []
      WAFRegionalIPSet: []
      WAFRegionalIPSetIP: []
      WAFRegionalRateBasedRule: []
      WAFRegionalRateBasedRulePredicate: []
      WAFRegionalRegexMatchSet: []
      WAFRegionalRegexMatchTuple: []
      WAFRegionalRegexPatternSet: []
      WAFRegionalRegexPatternString: []
      WAFRegionalRule: []
      WAFRegionalRulePredicate: []
      WAFRegionalWebACL: []
      WAFRegionalWebACLRuleAttachment: []
      WAFRule: []
      WAFWebACL: []
      WAFWebACLRuleAttachment: []
      WorkSpacesWorkspace: []
